export const APP_NAME = "Mermão Clothes";

export const LABELS = {
  LB_HOME: "Inicio",
  LB_SHOP: "Loja",
  LB_ACCOUNT: "Minha Conta",
  LB_ABOUT: "Sobre",
  LB_CART: "Carrinho",
  LB_CATEGORYS: "Categorias",
  LB_FILTER_PRICE: "Filtrar por preços até",
  LB_POLITICAS_PRIVACIDADE: "Politicas de Privacidade",
  LB_CONDICOES_GERAIS: "Condições Gerais",
};

export const PLACEHOLDERS = {
  INPUT_EMAIL: "Digite seu e-mail",
  INPUT_SENHA: "Digite sua senha",
  INPUT_CONFIRMA_SENHA: "Confirma sua senha",
  INPUT_LOGRADOURO: "Endereço",
  INPUT_BAIRRO: "Bairro",
  INPUT_CIDADE: "Municipio",
  INPUT_ESTADO: "Estado / UF",
  INPUT_COMPLEMENTO: "Complemento",
  INPUT_NUMERO: "Numero",
  INPUT_CEP: "CEP",
  INPUT_TIPO_IGREJA: "Tipo da Igreja",
  INPUT_NOME_USERNAME: "Nome de Usuario",
  INPUT_NOME_IGREJA: "Nome da Igreja",
  INPUT_LIDER_IGREJA: "Lider da Igreja",
  INPUT_NOME_TIPO_IGREJA: "Nome Tipo da Igreja",
  INPUT_CNPJ_IGREJA: "CNPJ",
  INPUT_DESCRICAO_IGREJA: "Mensagem",
  INPUT_DESCRICAO_TIPO_IGREJA: "Descrição",
  INPUT_TIPO_CONTATO: "Tipo de Contato",
  INPUT_WHATSAPP_CONTATO: "WhatsApp",
  INPUT_EMAIL_CONTATO: "Email",
  INPUT_SITE_CONTATO: "Site",
  INPUT_NOME_MEMBRO: "Nome Completo",
  INPUT_CPF_MEMBRO: "CPF",
  INPUT_GENERO_MEMBRO: "Gênero",
  INPUT_ESTADO_CIVIL_MEMBRO: "Estado Civil",
  INPUT_TIPO_MEMBRO: "Tipo de Membro",
  INPUT_CARGO_MEMBRO: "Selecione um cargo",
  INPUT_DT_NASCIMENTO_MEMBRO: "Data de Nasc.",
  INPUT_DT_CONVERSAO_MEMBRO: "Data de Conversão",
  INPUT_DT_BATISMO_MEMBRO: "Data de Batismo",
  INPUT_LISTA_IGREJAS: "Selecione a Igreja",
  INPUT_LISTA_MEMBROS: "Selecione o Membro",
  INPUT_LISTA_LIDER: "Selecione o Lider",
  INPUT_LISTA_CURSOS: "Selecione o Curso",
  INPUT_LISTA_CLASSE: "Selecione a Classe",
  INPUT_LISTA_DE_DIAS: "Dia da Semana",
  INPUT_PROGRAMACAO_HORA: "Hora de Inicio",
  INPUT_NOME_CARGOS: "Nome do Cargo",
  INPUT_NOME_CURSOS: "Nome do Curso",
  INPUT_NOME_CLASSE: "Nome da Clase",
  INPUT_PROFESSOR_CURSOS: "Professor(a) da Classe",
  INPUT_CATEGORIA_CURSOS: "Selecione a Categoria",
  INPUT_STATUS_CURSOS: "Situação",
  INPUT_STATUS_MEMBROS: "Situação",
  INPUT_STATUS_ALUNOS: "Situação",
  INPUT_STATUS_USERS: "Tipo de Usuário",
  INPUT_DESCRICAO_CARGOS: "Descrição",
  INPUT_DESCRICAO_CURSOS: "Descrição",
  INPUT_URL_NOTICIA: "Url",
  INPUT_TITULO_NOTICIA: "Titulo",
  INPUT_DESCRICAO_NOTICIA: "Descrição",
  INPUT_TITULO_VIDEO: "Titulo do Video",
  INPUT_DESCRICAO_VIDEO: "Descrição",
  INPUT_URL_VIDEO: "URL do Youtube",
  INPUT_NOME_SUPORTE: "Nome",
  INPUT_DESCRICAO_SUPORTE: "Descrição",
  INPUT_EMAIL_SUPORTE: "Email",
};
